### ISSUE TITLE
Setear asignación

### ISSUE THREAD

**Issue by EsperanzaMacarena** [lmlopezmagana/satapp#11]
Buenas Luismi,

Al crear un ticket con un tecnico asignado, el estado siempre es sin asignar, estaría interesante que si encuentra tecnico en el body, que la api ponga a ese ticket el estado ASIGNADA, así como a la hora de asignar un técnico más tarde. ¿Qué piensas?

**Comment by lmlopezmagana** [comment]
Solucionado en 7c6ff91a75aace911889a12a0717efe7ea8b1992

Al crear un ticket, si incluye el técnico, cambia el estado a ASIGNADA.
