### ISSUE TITLE
Error en DELETE /anotacion/:id

### ISSUE THREAD

**Issue by DanielSantanoF** [lmlopezmagana/satapp#12]
La petición DELETE /anotacion/:id para borrar una anotación borra todas las anotaciones relacionadas con un ticket:

Datos de muestra -> 
-Tenemos un ticket con varias anotaciones:
![error1](https://user-images.githubusercontent.com/45068977/75974851-c4be3200-5ed7-11ea-8c6b-d3f7693f2b44.PNG)

-Borramos su segunda anotación (aunque borrando cualquier también pasa en este caso borramos la segunda del array):
![error2](https://user-images.githubusercontent.com/45068977/75974894-dacbf280-5ed7-11ea-9b5e-d7af75b7f4be.PNG)

-Revisamos si se ha borrado correctamente y vemos que ha borrado no solo la indicada si no todas:
![error3](https://user-images.githubusercontent.com/45068977/75974929-ec14ff00-5ed7-11ea-99c2-3f493d9faafb.PNG)

**Comment by myrows** [comment]
@DELETE /anotaciones/:id - Error 404

**Comment by DanielSantanoF** [comment]
Al borrar la anotación la indicada por id se borra, las demás anotaciones no se borran de la base de datos pero la respuesta del ticket por id te devuelve el array de anotaciones vació.

**Comment by lmlopezmagana** [comment]
Solucionado en d4ca3584a65638e5eaeeae184f2fc95bce8777ff
