### ISSUE TITLE
Error en la documentación de cambio de password

### ISSUE THREAD

**Issue by cads918** [lmlopezmagana/satapp#14]
En la documentación aparece que hay que pasarle la password como parametro y en realidad hay que passarla como body.

**Comment by lmlopezmagana** [comment]
Revisando la documentación generada por apidocs, siempre indica que hay que pasar como parámetros tanto lo que recibe en el Query como lo que debe recibir por el Body. Se aclara que la contraseña debe ir en el cuerpo de la petición y se cierra la indicencia.
