### ISSUE TITLE
No existe en la api obtener imagen de ticket en el controller

### ISSUE THREAD

**Issue by juanantoniolago** [lmlopezmagana/satapp#17]

**Comment by lmlopezmagana** [comment]
Cada ticket, cuando tiene alguna foto, devuelve un array con las fotos disponibles, con la ruta de la petición que hay que realizar. Suele tener esta estructura `/ticket/img/<idDelTicket>/<indexDeLaFoto>`

```json
{
"fotos": [
        "/ticket/img/5e61fe3743f965436bf02c34/0",
        "/ticket/img/5e61fe3743f965436bf02c34/1"
    ]
}
```
