### ISSUE TITLE
Usuario técnico GET /users -> 401

### ISSUE THREAD

**Issue by DanielSantanoF** [lmlopezmagana/satapp#18]
En las funcionalidades de la app indicas:
Tan solo los usuarios administradores o técnicos podrán asignar las incidencias a un usuario técnico. Cuando una incidencia se asigna a un técnico, se guarda el técnico y la fecha de la misma.

Pero el usuario técnico no puede hacer la petición GET /users dado que da código de error 401 Unauthorized, de tal manera que no tiene acceso a la lista de usuarios para seleccionar el técnico
 al que asignarle el ticket.

![error401](https://user-images.githubusercontent.com/45068977/76067071-0c53c500-5f8f-11ea-899f-9683528fb326.PNG)

**Comment by lmlopezmagana** [comment]
Resuelto en el commit fdaf5e6fe86560f78b36df8ba51def74fec6fd23
