### ISSUE TITLE
Error al hacer get a la imagen del usuario

### ISSUE THREAD

**Issue by DanielSantanoF** [lmlopezmagana/satapp#2]
![ErrorGetUserPicture](https://user-images.githubusercontent.com/45068977/75436683-4997d180-5955-11ea-972f-03c9e0d71da7.PNG)

**Comment by lmlopezmagana** [comment]
¿Puedes aportar los datos con los que los has probado?

Un saludo.

**Comment by lmlopezmagana** [comment]
Debe estar resuelta a partir del commit e5a083712c94836091eb2c4070b51428a6db800f

**Comment by lmlopezmagana** [comment]
Se realiza algún ajuste más en el commit a8f162eb7f2c888b5060b491caad0e78e5457329
- Ya sí que devuelve el 404 y no da fallo
- El usuario no debería tener el campo _picture_ si el usuario no da de alta una imagen

**Comment by DanielSantanoF** [comment]
Issue arreglado da 404 si el usuario no tiene foto y si tiene te la devuelve de manera correcta
