### ISSUE TITLE
Error 500 en POST /ticket

### ISSUE THREAD

**Issue by EsperanzaMacarena** [lmlopezmagana/satapp#3]
Cuando creo un ticket con los campos título, descripción y fotos, no hay problema, pero cuando quiero crear un ticket con técnico también, me da un error 500. Por lo que he leído en la documentación, hay que pasarle el ID del técnico. La consulta sería la siguiente

![imagen](https://user-images.githubusercontent.com/45162642/75771020-682d0c80-5d49-11ea-961c-59e5ecbc6b32.png)

El token es el del admin y el id es el de un usuario tecnico.

**Comment by EsperanzaMacarena** [comment]
Log de Heroku
![imagen](https://user-images.githubusercontent.com/45162642/75771431-441dfb00-5d4a-11ea-8911-6903bdc2e9f6.png)

**Comment by lmlopezmagana** [comment]
Solucionado
