### ISSUE TITLE
Error en petición PUT /ticket/:id

### ISSUE THREAD

**Issue by DanielSantanoF** [lmlopezmagana/satapp#4]
Cuando hace un update a un ticket la petición se hace correctamente si envías todos los query y autenticación, devuelve un 200 OK el problema es que no edita los campos simplemente los elimina al hacer el update no te devuelve los campos de titulo y descripcion y si pruebas a traerte todos los tickets tampoco aparecen dichos campos.
PETICIÓN UPDATE:
![error1](https://user-images.githubusercontent.com/45068977/75775546-7c293c00-5d52-11ea-8621-77e5b6bac976.PNG)
PETICIÓN GET (todos los tickets):
![error2](https://user-images.githubusercontent.com/45068977/75775576-8f3c0c00-5d52-11ea-8050-1317e5cfe40a.PNG)

**Comment by lmlopezmagana** [comment]
¡Hola!

No me queda muy claro el problema. Es decir, no sé si realmente el problema está en lo que hace (o no hace) el API al modificar, o bien en lo que devuelve una vez modificado. 

El código de modificación hace lo siguiente:

`export const update = ({ user, bodymen: { body }, params }, res, next) =>
  Ticket.findById(params.id)
    .populate('creado_por')
    .then(notFound(res))
    .then(authorOrAdmin(res, user, 'creado_por'))
    .then((ticket) => ticket ? Object.assign(ticket, body).save() : null)
    .then((ticket) => ticket ? ticket.view(true) : null)
    .then(success(res))
    .catch(next)
`

Busca el ticket, y entre otras cosas, le asigna los valores que se pasan en el body a los diferentes campos del ticket. Es decir, que básicamente cambia cada dato del ticket por el nuevo dato.

¿Puedes comprobar si el cambio tampoco se realiza en la base de datos y el problema está, entonces, en el objeto que retorna la petición PUT?

Un saludo.

**Comment by DanielSantanoF** [comment]
El problema que me encontré es que al modificar un ticket y enviar los
nuevos valores de "titulo" y "descripcion" no los actualiza si no que al
editar el ticket deja de enviar dichos valores como si los borrase, no
envía los valores ni en la respuesta del PUT ni en ninguna otra petición
relacionada como el GET a todos los tickets
