### ISSUE TITLE
Error en petición GET /anotaciones/ticket

### ISSUE THREAD

**Issue by myrows** [lmlopezmagana/satapp#6]
No encuentro la forma de traer todas las anotaciones de un ticket, la petición no da la posibilidad de identificarlo por su id.

**Comment by lmlopezmagana** [comment]
En la versión 1.1.3 se añade la posibilidad de que al obtener un ticket, en lugar de obtener un array con los ids de las anotaciones, se obtengan todos los datos de dichas anotaciones.

Necesita testearse para comprobar que funciona.

**Comment by lmlopezmagana** [comment]
Se soluciona en el commit  dda8a934a3e44c04d7589c08d282bf076e708e70.

La petición de obtener un ticket por su ID incluye el contenido de todas las anotaciones que tenga.
